---
general:
  pipeline: "sap-cloud-sdk"
  buildTool: "mta"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false
  Release:
    cloudFoundryDeploy: true
    tmsUpload: false
  steps:
    cloudFoundryDeploy:
      cloudFoundry:
        apiEndpoint: "https://api.cf.eu10.hana.ondemand.com/"
        org: "CLD200-CF-A02"
        space: "dev"
        credentialsId: "cfdeploy"
        appName: ""
      mtaDeployParameters: "-f --version-rule ALL"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
